### ISSUE TITLE
Not able to execute this project 

### ISSUE THREAD

**Issue by aqsahashmi** [vnep-approx/evaluation-acm-ccr-2019#1]
[Doc1.docx](https://github.com/vnep-approx/evaluation-acm-ccr-2019/files/2924207/Doc1.docx)

**Comment by aqsahashmi** [comment]
guide me how to run this project

**Comment by MatthiasRost** [comment]
Will do so in due time. We are currently working on the documentation. Will let you know once the documentation and the results are there.

**Comment by aqsahashmi** [comment]
ok please let me know when u finish your work really want to work in this
project but facing difficulties

**Comment by aqsahashmi** [comment]
sir while executing the code i am getting this error please tell me how to
resolve this issue thank you.

**Comment by aqsahashmi** [comment]
[
![image](https://user-images.githubusercontent.com/47491761/53934065-3302c580-40c7-11e9-8843-3a51431c141a.png)

**Comment by MatthiasRost** [comment]
The source code is now released with the relevant data. Sorry for taking so long.
